# Generated by Django 4.0.9 on 2023-02-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thup',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
