# Generated by Django 4.1.2 on 2023-02-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_brand_category_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumb',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
