# Generated by Django 4.0.9 on 2023-03-06 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_thup'),
        ('shop', '0005_cartitem'),
    ]

    operations = [
    ]
