# Generated by Django 4.0.9 on 2023-03-10 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_merge_0002_product_thup_0005_cartitem'),
        ('shop', '0006_order_orderproduct'),
    ]

    operations = [
    ]
